### ISSUE TITLE
Error when compiling classification.py

### ISSUE THREAD

**Issue by vincehass** [AlexImmer/BNN-predictions#1]
Hi, I am trying to reproduce the paper results, however I got this error:

Traceback (most recent call last):
  File "/Users/vince/BNN-predictions-main/experiments/classification.py", line 236, in <module>
    train=True, double=double)
  File "/Users/vince/BNN-predictions-main/preds/datasets.py", line 167, in __init__
    'waveform', 'satellite', 'digits', 'banana'], error_msg
AssertionError: invalid UCI classification dataset

If you have some thought how to fix it I will appreciate.
Thank you again!

**Comment by aleximmer** [comment]
Hi, sorry for the inconvenience. Could you tell me how it got to the error so I can reproduce it? Which script did you try to run precisely? It seems like `python classification.py` but maybe the `--dataset` argument was not set or to an incorrect value?

**Comment by vincehass** [comment]
Hi thank you for your quick reply,

Actually I did not make any modification in the code neither in the data folder. I just run : python classification.py
It seems that "preds/dataset.py" raise an error in here:

def __init__(self, data_set, split_train_size=0.7, random_seed=6, shuffle=True, stratify=None,
                 root=DATA_DIR, train=True, valid=False, scaling=True, double=False):

        assert isinstance(random_seed, int), 'Please provide an integer random seed'
        error_msg = 'invalid UCI classification dataset'
        assert data_set in ['australian', 'breast_cancer', 'glass', 'ionosphere', 'vehicle',
                            'waveform', 'satellite', 'digits', 'banana'], error_msg
 
Thanks for your help!

**Comment by aleximmer** [comment]
Thanks for the details. The problem is that `python classification.py` requires some arguments. In particular, the dataset argument is missing it seems. Can you try `python classification.py --dataset australian`? I missed to flag these arguments as required but I will push a fix to that now. For the parameters you can pass, see the argparse section of https://github.com/AlexImmer/BNN-predictions/blob/main/experiments/classification.py. 

Alternatively, you can find example commands here: https://github.com/AlexImmer/BNN-predictions/blob/main/experiments/uci_classification_commands.py. Simply running `python uci_classification_commands` will print a bunch of commands that one can run for the benchmark.

**Comment by vincehass** [comment]
Hi @AlexImmer,
Thank you to point this out, really appreciated!
