### ISSUE TITLE
Uncertainty quantification for glm predictive

### ISSUE THREAD

**Issue by vincehass** [AlexImmer/BNN-predictions#2]
Hi,

I was wondering if it is possible to include code to reproduce the aleatoric and epistemic uncertainty shown in figure B.3?

Thank you!

**Comment by aleximmer** [comment]
Hi! That shouldn't be a problem. 
@maciejkorzepa: do you have the code for this and can add it briefly? Maybe to the toy classification notebook for completeness.

**Comment by maciejkorzepa** [comment]
I'll try to add it over the weekend.

**Comment by maciejkorzepa** [comment]
The calculation of the aleatoric and epistemic uncertainty is now added to the toy classification notebook. Please note that there are some differences - in the added example I plot variance instead of the standard deviation, the model architecture is slightly different and of course the dataset is different. However, the computation of the quantities is essentially the same.

**Comment by vincehass** [comment]
Thank you @maciejkorzepa very appreciated. I 'll probably open a "pull request" to add some experiments visualization in the near future.
